server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name web.lab.test;

    root /var/www/aws-devops-infrastructure-lab/current;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}

server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;

    server_name web.lab.test;

    root /var/www/aws-devops-infrastructure-lab/current;
    index index.html;

    ssl_certificate /etc/nginx/ssl/web.lab.test/web.lab.test.crt;
    ssl_certificate_key /etc/nginx/ssl/web.lab.test/web.lab.test.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:TLS:10m;
    ssl_session_timeout 1d;
    ssl_session_tickets off;

    location / {
        try_files $uri $uri/ =404;
    }
}
